const path = require('path');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const isProduction = process.env.NODE_ENV === 'production';
const webpack = require('webpack');

module.exports = {
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'public'),
    filename: './assets/js/index.js',
    // Change clean option to preserve existing files in public directory
    // Only clean the assets directory which is generated by webpack
    clean: {
      keep: /^(?!assets\/).*$/ // Keep all files/directories that are not under assets/
    },
  },
  devtool: "source-map",
  plugins: [
    // MiniCssExtractPlugin means that CSS will be extracted into a separate file instead of being inlined in the JS bundle.
        new MiniCssExtractPlugin({
          filename: './assets/css/[name].css',
          chunkFilename: './assets/css/[id].css',
        }),
        new CopyWebpackPlugin({'patterns': [
            {from:'./src/scss/images', to:'./assets/css/images'},
            {from:'./src/scss/fonts', to:'./assets/css/fonts'},
            {from: './node_modules/bootstrap-icons/font/fonts', to: './assets/css/fonts'},
            {from: './node_modules/jquery-colorbox/example2/images', to: './assets/css/images'},
        ]}), 
        // copies the entire directory 1 to 1, but you can do it with lodash src="<%=require('./src/images/logo.png')%>"

        new webpack.ProvidePlugin({
          $: "jquery",
          jQuery: "jquery",
          jquery: 'jquery',
          "window.jQuery": 'jquery',
        }), //Most legacy modules rely on the presence of specific globals, like jQuery plugins do on $ or jQuery. Configure webpack, to prepend var $ = require("jquery") everytime it encounters the global $ identifier.
  ],
  devServer: {
    static: {
      directory: path.join(__dirname, 'public'),
    },
    hot: true,
    port: 8080,
    devMiddleware: {
      writeToDisk: true,
    },
    open: false,
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
        },
      },
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader'], // Translates CSS into CommonJS
      },
      {
        test: /\.scss$/,
        use: [
          // 'style-loader' means that CSS will be injected into the DOM via a <style> tag.
          isProduction? 'style-loader' : MiniCssExtractPlugin.loader,
          { 
              loader: "css-loader",
              options: {
                  url: false,
                  sourceMap: true
              }
          },
          {
          loader: 'postcss-loader',
              options: {
                postcssOptions: {
                  plugins: () => [
                    require('autoprefixer')
                  ]
                }
              }
          },
          {
            loader: 'sass-loader',  
            options: {
              sourceMap: true,
              sassOptions: {
                //suppress deprecation warnings related to "mixed-decls" and "import" keep your build output cleaner
                silenceDeprecations: ['mixed-decls', 'import'],
                //originate from dependencies = node_modules folder
                quietDeps: true,
                //generally silences most output from the tool
                //quiet: true,
              },
            },
          }
        ],
      },
      {
        test: /\.svg$/,
        use: ['@svgr/webpack'],
      },
    ],
  },
  resolve: {
    extensions: ['.js', '.jsx'],
  },
};
